# Generated by Django 5.2.7 on 2025-11-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="well",
            name="notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="well",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
